/// <reference types="cypress" />

import { faker } from '@faker-js/faker';

describe('Checkout:', function(){

    beforeEach(function() {
        cy.visit('/')
        cy.fixture('products').then((product) => {
            this.product = product
        })
    })

    it('should checkout with a single item', function() {
        cy.addItemToCart_UI(this.product[0])
        cy.contains('.btn-success', 'Place Order').click()
        cy.get('.modal-header #orderModalLabel').should('be.visible').should('have.text', 'Place order')
        cy.get('form #totalm').should('contain', this.product[0].price)
        cy.get('form #name').click().type(faker.name.firstName())
        cy.get('form #country').click().type('US')
        cy.get('form #city').click().type(faker.address.city())
        cy.get('form #card').click().type(faker.finance.creditCardNumber('visa'))
        cy.get('form #month').click().type(faker.date.month())
        cy.get('form #year').click().type('2036')
        cy.contains('.btn-primary', 'Purchase').click()
        cy.get('.sweet-alert').should('be.visible')
        cy.get('.sweet-alert h2').should('contain', 'Thank you for your purchase!')
        cy.get('.sweet-alert p').should('contain.text', 'Amount: '+this.product[0].price)
        cy.contains('.sweet-alert button', 'OK').click()
    })
    it('should checkout with multiple items, validate totals', function() {
        cy.addItemToCart_UI(this.product[0])
        cy.addItemToCart_UI(this.product[1])
        cy.contains('.btn-success', 'Place Order').click()
        cy.get('.modal-header #orderModalLabel').should('be.visible').should('have.text', 'Place order')
        cy.get('form #totalm').should('contain', this.product[0].price + this.product[1].price)
        cy.get('form #name').click().type(faker.name.firstName())
        cy.get('form #country').click().type('US')
        cy.get('form #city').click().type(faker.address.city())
        cy.get('form #card').click().type(faker.finance.creditCardNumber('visa'))
        cy.get('form #month').click().type(faker.date.month())
        cy.get('form #year').click().type('2036')
        cy.contains('.btn-primary', 'Purchase').click()
        cy.get('.sweet-alert').should('be.visible')
        cy.get('.sweet-alert h2').should('contain', 'Thank you for your purchase!')
        cy.get('.sweet-alert p').should('contain.text', 'Amount: '+(this.product[0].price + this.product[1].price))
        cy.contains('.sweet-alert button', 'OK').click()
    })
    it('while authenticated, should checkout and validate cart is cleared after checkout', function() {
        cy.login_via_UI(Cypress.env('USERNAME'), Cypress.env('PWD'))
        cy.clearCart_via_UI(Cypress.env('USERNAME'))
        cy.addItemToCart_UI(this.product[1])
        cy.contains('.btn-success', 'Place Order').click()
        cy.get('.modal-header #orderModalLabel').should('be.visible').should('have.text', 'Place order')
        cy.get('form #totalm').should('contain', this.product[0].price)
        cy.get('form #name').click().type(faker.name.firstName())
        cy.get('form #country').click().type('US')
        cy.get('form #city').click().type(faker.address.city())
        cy.get('form #card').click().type(faker.finance.creditCardNumber('visa'))
        cy.get('form #month').click().type(faker.date.month())
        cy.get('form #year').click().type('2036')
        cy.contains('.btn-primary', 'Purchase').click()
        cy.get('.sweet-alert').should('be.visible')
        cy.get('.sweet-alert h2').should('contain', 'Thank you for your purchase!')
        cy.get('.sweet-alert p').should('contain.text', 'Amount: '+this.product[0].price)
        cy.contains('.sweet-alert button', 'OK').click()
        cy.visit('/cart.html')
        cy.url().should('contain', '/cart.html')
        cy.get('tbody>tr').should('not.exist')
        cy.get('#totalp').should('be.empty')
    })
    it('should not allow checkout while key required info are missing (Name + Credid card number)', function() {
        cy.addItemToCart_UI(this.product[0])
        cy.contains('.btn-success', 'Place Order').click()
        cy.get('.modal-header #orderModalLabel').should('be.visible').should('have.text', 'Place order')
        cy.get('form #totalm').should('contain', this.product[0].price)
        cy.get('form #name').click().type(faker.name.firstName())
        cy.get('form #country').click().type('US')
        cy.get('form #city').click().type(faker.address.city())
        cy.get('form #month').click().type(faker.date.month())
        cy.get('form #year').click().type('2036')
        cy.contains('.btn-primary', 'Purchase').click()
        cy.on('window:confirm', (str) => {
            expect(str).to.equal(`Please fill out Name and Creditcard.`)
          })
        cy.on('window:confirm', () => true)
        cy.get('form #name').click().clear()
        cy.get('form #card').click().type(faker.finance.creditCardNumber('visa'))
        cy.contains('.btn-primary', 'Purchase').click()
        cy.on('window:confirm', (str) => {
            expect(str).to.equal(`Please fill out Name and Creditcard.`)
          })
        cy.on('window:confirm', () => true)
        cy.get('form #name').click().type(faker.name.firstName())
        cy.contains('.btn-primary', 'Purchase').click()
        cy.get('.sweet-alert').should('be.visible')
        cy.get('.sweet-alert h2').should('contain', 'Thank you for your purchase!')
        cy.contains('.sweet-alert button', 'OK').click()
    })
    it('should not checkout while user decides to cancel placing the order', function(){
        cy.addItemToCart_UI(this.product[0])
        cy.contains('.btn-success', 'Place Order').click()
        cy.get('.modal-header #orderModalLabel').should('be.visible').should('have.text', 'Place order')
        cy.get('form #totalm').should('contain', this.product[0].price)
        cy.get('form #name').click().type(faker.name.firstName())
        cy.get('form #country').click().type('US')
        cy.get('form #city').click().type(faker.address.city())
        cy.get('form #card').click().type(faker.finance.creditCardNumber('visa'))
        cy.get('form #month').click().type(faker.date.month())
        cy.get('form #year').click().type('2036')
        cy.contains('.btn-secondary', 'Close').click({force: true})
        cy.visit('/cart.html')
        cy.url().should('contain', '/cart.html')
        cy.contains('tbody>tr>td', this.product[0].title).should('be.visible')
        cy.contains('tbody>tr>td', this.product[0].price).should('be.visible')
        cy.get('#totalp').should('contain', this.product[0].price)
    })
    it('should not allow checkout while the cart is empty', function(){
        cy.visit('/cart.html')
        cy.contains('.btn-success', 'Place Order').click()
        cy.get('.modal-header #orderModalLabel').should('be.visible').should('have.text', 'Place order')
        cy.get('form #name').click().type(faker.name.firstName())
        cy.get('form #country').click().type('US')
        cy.get('form #city').click().type(faker.address.city())
        cy.get('form #card').click().type(faker.finance.creditCardNumber('visa'))
        cy.get('form #month').click().type(faker.date.month())
        cy.get('form #year').click().type('2036')
        cy.contains('.btn-primary', 'Purchase').click()
        cy.get('.sweet-alert').should('not.be.visible')
        cy.get('.sweet-alert h2').should('not.contain', 'Thank you for your purchase!')
        cy.contains('.sweet-alert button', 'OK').click()
        // BUG here!!
    })
})